[package]
name = "walk"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
edition = "2018"

[dependencies]
syscall = "0.2"
libc = "0.2"
arrayvec = {version = "0.4", default-features = false}
crossbeam-channel = "0.3"
num_cpus = "1.0"

[profile.release]
debug = 1
lto = true
